services:
  - type: web
    name: adhd-assistant-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd hi && python backend1.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: 10000

  - type: web
    name: adhd-assistant-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd hi && streamlit run frontend1.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: BACKEND_URL
        value: https://adhd-virtual-assistant-2.onrender.com
      - key: PORT
        value: 10001
      - key: STREAMLIT_SERVER_PORT
        value: 10001
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
