services:
  - type: web
    name: adhd-assistant-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend1.py
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: RENDER
        value: "true"

  - type: web
    name: adhd-assistant-frontend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend1.py
    envVars:
      - key: BACKEND_URL
        value: https://adhd-assistant-backend.onrender.com/chat
      - key: RENDER
        value: "true"
